### ISSUE TITLE
Add React todos tutorial

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs#1034]
[The todos app tutorial ](https://docs.blockstack.org/build-apps/tutorials/todos)is based on a React app that has been restructured to use `connect` instead of `connect-react`.

While this is helpful to a broader range of JavaScript developers, we should restore a version of the tutorial and app with `connect-react` usage for React developers.

**Comment by pgray-hiro** [comment]
After discussion with @aulneau regarding the Todos App tutorial and making sure we cover all methods of implementing`connect`, do you think this issue is still relevant?  We do have a section in the Todo's tutorial that specifically provides example code on how to implement the `useConnect` hook, which should be clear to any React developer.  Longer term I do think I'd like a React specific tutorial, but maybe not the Todos app.  Thoughts @markmhx ?

**Comment by markmhx** [comment]
I agree, we'd do better to create a new React app than reworking the todos app with React. And the current example code for the `userConnect` hook is probably sufficient until we have a new non-React app in place that shows the wider range of Stacks 2.0 functionality. Then medium to long-term we can create a React version of it – or probably even better, a separate React app that shows a separate use case so we minimize redundancy.

**Comment by pgray-hiro** [comment]
I'm going to close this issue then, I think we are likely to get a pretty good React app demonstration from the Hackathon next week.
