### ISSUE TITLE
Populate Stacks.js/connect-react README 

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs#1035]
[The README for the Stacks.js/connect-react package](https://github.com/blockstack/ux/tree/master/packages/connect-react) should be populated with API reference information then linked from the "Build apps" navigation in documentation.

![image](https://user-images.githubusercontent.com/28991/104326389-fb96a880-54e9-11eb-80db-43b1f1c0cae7.png)

![image](https://user-images.githubusercontent.com/28991/104326780-6516b700-54ea-11eb-8c2e-8404036d3d8a.png)

**Comment by pgray-hiro** [comment]
@markmhx This issue is halfway complete, I added `@stacks/connect` to the sidebar, and made the link to the correct repo (https://github.com/blockstack/connect).  The READMEs for the base repo and `@stacks/connect-react` and `@stacks/connect-ui` are not populated though.  The text of the README for `@stacks/connect-ui` appears to be boilerplate for a Stencil component.

I'm going to kick this over to UserX and request developer assistance in populating those READMEs.

**Comment by markmhx** [comment]
@andresgalante this may be worth a sync convo with the team to figure out how we want to approach.
