### ISSUE TITLE
Distinguish Clarity functions from special forms

### ISSUE THREAD

**Issue by njordhov** [blockstack/docs#495]
The [Clarity function reference](https://docs.blockstack.org/core/smart/clarityref#function-reference) includes entries that aren't _functions_  but _special forms_ that should be grouped separately. 

This include the many `define-*` constructs and `tuple`, all of which doesn't call their evaluated arguments like normal functions but rather are evaluated in special ways.

**Comment by njordhov** [comment]
Other special forms: 

    as-contract
    at-block
    begin
    if
    let
    and
    or

**Comment by agraebe** [comment]
I think the goal of this issue is to create a new chapter on the reference page, just for special forms. This would include updates in:

- https://github.com/blockstack/docs/blob/master/src/_data/clarity-reference.json#L2
- https://github.com/blockstack/docs/blob/master/src/common/data/clarity-ref.ts#L23

**Comment by friedger** [comment]
@agraebe This should be reopened as #867 does not solve this issue!

**Comment by agraebe** [comment]
ah, my mistake! yes, let's re-open
