### ISSUE TITLE
Revamp docs landing page

### ISSUE THREAD

**Issue by johndmulhausen** [blockstack/docs#638]
We think this could help serve the outcome of "App developers who want to set up IDs and storage in an app" identified by @jeffdomke. Currently this is not very fleshed out with other topic goals -- after all this is generally what the docs aim to do. However, the landing page could better orient people about our technology. The homepage in general is a bit old and probably not what we want to serve people when eyes are on us for mainnet launch.

**Comment by aulneau** [comment]
One thing we should discuss relating to this is where the homepage will be. I think we should integrate it directly with the next.js application we're using for the docs, rather than it being in webflow. If we want to utilize some aspects of the webflow cms, that's totally possible. I think we should avoid having two separate sites though (one for homepage and one for the rest of the docs). It would be a much better experience for them to be combined.
