### ISSUE TITLE
Add instructions for Windows machines

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#661]
All documentation is optimized for unix machines. Windows developers are facing issues completing the steps.

The new docs system could have a code sample switch to help with that

**Comment by zrixes** [comment]
### Instructions for setting up STX miner on Windows PC

Before you begin, check that you have the necessary software installed on your PC:

[Rust](https://www.rust-lang.org/tools/install), [Microsoft C++ Build Tools 2019](https://visualstudio.microsoft.com/visual-cpp-build-tools/)(C++ build tools), [Git](https://git-scm.com/downloads) , [node.js](https://nodejs.org/en/download/) and [Python](https://www.python.org/downloads/)

Tutorials that I’ve relied upon while writing this walkthrough

- Blockstack – Running a Testnet node – [direct link](https://docs.blockstack.org/stacks-blockchain/running-testnet-node)
- Blockstack – Mine Stacks Token – [direct link](https://docs.blockstack.org/mining)

Once you have all software installed, power up your command prompt and insert your first command:

`git clone https://github.com/blockstack/stacks-blockchain.git` #This is to download stacks blockchain files on to your computer

Subsequently once installation is done, proceed with the second part of the command:

`cd stacks-blockchain` #This is to set the pathway pointing towards stacks-blockchain folder on your PC

Next, copy the following to your command prompt: `cargo build --workspace --release --bin stacks-node`

It’ll take a couple of minutes for the program to run.. Once its done, proceed with the next command:

You will have to ensure that the pathway is pointing towards “stacks-blockchain/target/release”. Thus from your current pathway C:\Users\ **User** \stacks-blockchain> type: `cd /target/release`

#Note the second User(in **bold**) above will be your PC name, for me I've named it User. 

Once the pathway is set, type: `stacks-node krypton` #This is to run the stacks node, Krypton is the current testnet phase, once mainnet a different name will be used

If you’re prompted with an error message that says panic thread
![image](https://user-images.githubusercontent.com/19296178/98454607-5a197080-21a1-11eb-8697-b7c3048581ce.png)

It could be due to your stacks node executable file not being the latest version. Download the latest Blockstack release(windows-x64.zip) – [direct link](https://github.com/blockstack/stacks-blockchain/releases/) and overwrite the stacks-node on your PC with the latest file.

![image](https://user-images.githubusercontent.com/19296178/98454623-9c42b200-21a1-11eb-8add-423aa556c7f4.png)
Replace existing stacks-node file with the latest version

You will know that your node is running successfully if you see your log look something like this:

(INFO [1588108047.585] [src/chainstate/stacks/index/marf.rs:732] First-ever block 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206)
![image](https://user-images.githubusercontent.com/19296178/98454631-b7adbd00-21a1-11eb-990a-70df2184b0f2.png)


**Now you have your node up and running! Next it’ll be to set up STX miner.**

Press Crt + C in the command prompt to stop the above node from running.

Install `@stacks/cli` with the following command: `npm install --global @stacks/cli`

Subsequently type the following: `stx make_keychain -t > cli_keychain.json`

And finally to generate your keychain: `cli_keychain.json`

After your keychain is generated, remember to keep the information as you will need it later.
![image](https://user-images.githubusercontent.com/19296178/98454646-f17ec380-21a1-11eb-8099-c105ab9681d6.png)
Sample keychain info

Use the following command to get testnet BTC to your address:
`curl -XPOST https://stacks-node-api.blockstack.org/extended/v1/faucets/btc?address=<btc_address>`

![image](https://user-images.githubusercontent.com/19296178/98454662-2c80f700-21a2-11eb-8353-b0082a3acfcd.png)
Generating Keychain & replacing btcAddress

Replace the _<btc_address>_ with the chain of letters generated from your keychain _“btcAddress”_

#Please note that only during testnet phase that you insert testnet btcAddress and seephrase, in the case of mainnet, please insert a btcAddress that you own, along with its private key.

Thereafter, create a file using notepad with the following chain of commands:
```
 [node]
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node = "048dd4f26101715853533dee005f0915375854fd5be73405f679c1917a5d4d16aaaf3c4c0d7a9c132a36b8c5fe1287f07dad8c910174d789eb24bdfb5ae26f5f27@testnet-miner.blockstack.org:20444"
# Enter your private key here!
seed = "replace-with-your-private-key"
miner = true

[burnchain]
chain = "bitcoin"
mode = "krypton"
peer_host = "bitcoind.blockstack.org"
#process_exit_at_block_height = 5340
#burnchain_op_tx_fee = 5500
#commit_anchor_block_within = 10000
rpc_port = 18443
peer_port = 18444

[[mstx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000
[[mstx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000
[[mstx_balance]]
address = "ST1HB1T8WRNBYB0Y3T7WXZS38NKKPTBR3EG9EPJKR"
amount = 10000000000000000
[[mstx_balance]]
address = "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP"
amount = 10000000000000000
```
Replace the **seed** field with your private key. Save and close the configuration file and naming it: `testnet-miner-conf.toml`

Subsequently, head over to your stacks-blockchain folder. Generally this folder can be found in: `C:\Users\User\stacks-blockchain\testnet\stacks-node\conf` and place your newly created file in the location.
![image](https://user-images.githubusercontent.com/19296178/98454715-afa24d00-21a2-11eb-8dc6-e270cdf01ef4.png)
Sample picture of testnet-miner-conf.toml

Lastly, ensure that your pathway is C:\Users\User\stacks-blockchain\target\release> and proceed with the final command:

`stacks-node start --config=../../testnet/stacks-node/conf/testnet-miner-conf.toml`

Viola! Your miner node should be up and running.

![image](https://user-images.githubusercontent.com/19296178/98454726-ce084880-21a2-11eb-9d39-98969709938a.png)
Screenshot shows miner node up and running(lookout for "Miner node: starting up, UTXOs found" to indicate its working)

**Comment by HariniRajan397** [comment]
@zrixes  The instructions looks great. Very great effort ! I have tweaked it a bit and added the instructions for setting up both follower and miner node in Windows using Binary as per docs format and created a pull request.  

Sincere thanks and Kudos to you and @whoabuddy !

**Comment by agraebe** [comment]
wow, thanks so much @zrixes for the content and to @HariniRajan397 for the PR

**Comment by tvr132b** [comment]
great! documentation steps thanks @zrixes  and @HariniRajan397 . node is up and running now on my windows machine too .  One small step perhaps could be added post stacks-node krypton is  "allow access to stacks "  modal that popups due to windows privacy settings .
