### ISSUE TITLE
Feature: Language selection for sample code

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#667]
In many cases, we have sample codes that are not using JavaScript but Clarity/Bash/PowerShell/etc. A tab component would allow us to accommodate for that. 

For example, a windows developer could make API calls without having to figure out the equivalent of cURL.

**Comment by aulneau** [comment]
I've found that typically a language selector would be most useful when you can do the same thing in more than one language. An example being lets say we had connect for react, for vue, and for angular. Or we have blockstack.js but also a ruby implementation, or some other implementation. 

IMO it doesn't make sense to have one component that can switch between javascript and bash, because those are typically different steps in a process.

**Comment by agraebe** [comment]
Thinking about this... I believe we brought this up we we reviewed the developer testing insights. I don't feel strongly about this, certainly not the highest priority. But the main point was that the shell commands are different for Windows machines (e.g. cURL). Windows users do represent a big portion of developers, generally speaking.

I think this would create most value for things that can be accomplished with our libraries _or_ the CLI. One example could be contract call: cURL on unix, invoke on windows, lib code for js.
