### ISSUE TITLE
Add tutorial for using stack-blockchain-api-client

### ISSUE THREAD

**Issue by friedger** [blockstack/docs#779]
# Building a public registry

## Context:
For this tutorial, the reader is expected to have followed the todo list tutorial and the hello world clarity tutorial.
A smart contract exists that acts as a registey for public todo lists

The final app allows the user to
* register their todo list on the registry and view the progress of the transaction handling
* see and visit other registered todo lists

## Outline:
* Introduction
   * Reference to todo list and hello world tutorials
   * ~~Explain the purpose of the library in contrast to other libraries~~
   * Setup todo list and register button with contract call.
* Add library to web app
* Follow progress of transaction processing
* Query transactions for recent register calls
   * using the library
* Query read-only function (`get-last-todo-id` and `owner-of`)
   * ~~using curl~~
   * using the library 
* Query a data map entry ( `registry`)
   * ~~using curl~~
   * using the library
* Learn more
   * stacks-blockchain-api page
   * Client API Guide (to be written)

## Smart Contract
``` 
(define-non-fungible-token todo-nft uint)

(define-map registry
  ((todo-id uint))
  (
    (name (buff 30))
    (url (buff 255))
  )
)

(define-map lookup
  ((name (buff 30)))
  ((todo-id uint))
)

(define-data-var last-todo-id uint u0)

(define-data-var panic-trigger (optional bool) none)
(define-private (assert-panic (value bool))
  (if value true (unwrap-panic (var-get panic-trigger)))
)

(define-public (register (name (buff 30)) (url (buff 255)))
  (let ((todo-id (+ u1 (var-get last-todo-id))))
    (var-set last-todo-id todo-id)
    (unwrap-panic (nft-mint? todo-nft todo-id tx-sender))
    (assert-panic (map-insert registry {todo-id: todo-id} {name: name, url: url}))
    (assert-panic (map-insert lookup {name: name} {todo-id: todo-id}))
    (ok todo-id)
  )
)

(define-public (update (todo-id uint) (name (buff 30)) (url (buff 200)))
  (let ((owner (unwrap-panic (nft-get-owner? todo-nft todo-id))))
    (if (is-eq owner tx-sender)
      (begin
        (assert-panic (map-set registry {todo-id: todo-id} {name: name, url: url}))
        (assert-panic (map-set lookup {name: name} {todo-id: todo-id}))
        (ok true)
      )
      (err u1)
    )
  )
)

(define-private (token-id-for (name (buff 30)))
  (unwrap-panic (get todo-id (map-get? lookup {name: name})))
)

(define-read-only (owner-of (name (buff 30)))
  (nft-get-owner? todo-nft (token-id-for name))
)

(define-read-only (get-last-todo-id)
  (var-get last-todo-id)
)
``` 
Deployed at ST25GX7MJA4FGEYYH5E7EBW30BYA4VG4VC1XETXXZ.todo-registry
source code at https://github.com/friedger/clarity-smart-contracts/blob/master/contracts/experiments/todo-registry.clar

**Comment by markmhx** [comment]
@friedger how's this effort been going? Anything I can do to help?

**Comment by friedger** [comment]
@markmhx please provide feedback whether the outline fit into the overall docs and whether this issue is good to work on.

In particular using the to-do app as the base

**Comment by agraebe** [comment]
@friedger, so awesome to see this! I have a few notes/suggestions:

- I'd assume it is best to put this tutorial into the "Smart Contracts" category (https://docs.blockstack.org/smart-contracts/overview). The focus being "how to interact with contracts using the API client". With that in mind, I'd walk through the contract and explain the functions briefly in the beginning and then pivot to the interaction part

- I think we'd generally benefit from a "Client API Guide". Something that lays out the features and shows code samples to accomplish them. This is where I'd put the "explain the purpose of the library in contrast to other libraries". The reason is that for a tutorial, Clarity developers might not want the full scoop - that would rather confuse them and diverge from the learning journey.

- minor: the API reference now includes the RPC reference, there are no different pages for that anymore. should help avoid complexity

- I like the idea to show both the library and cURL usage. Based on past developer tests, I'm sure folks would get confused by that though. Maybe the cURL sample is better positioned inside the API reference page or an API client guide?

- I'm assuming you'll need the transactions-js library to encode clarity values and construct transactions, right?

- We will soon release a monorepo for stacks.js (including transactions and networking package). that will impact the sources of this tutorial I'd assume slightly, but shouldn't be a blocking item

**Comment by friedger** [comment]
@agraebe Thank you for your comments. Make sense to me.

The transaction library comes already with Connect that is used already in the to-do app.

I will start writing now and send early screenshots to discuss the design of the UI.

**Comment by markmhx** [comment]
From a UX perspective, I wonder if it'd be more meaningful to register the completion of specific todos on the blockchain instead of the todo lists themselves. This could manifest itself as an extended option of the current todos app, in that you can mark tasks as completed as normal (in Gaia) or additionally mark them as completed _permanently_ (on chain). This could be framed as a more meaningful social action, since others can programmatically and non-programmatically rely on detecting that value to confirm whether you've completed / attested to a particular action.

A list registry should work fine as-is from a technical perspective if you want to move forward with that approach. But perhaps the todo-based permanent publishing will serve as a better "a-ha moment" for those wondering about the user value to signing transactions within apps.

<img width="734" alt="Screen Shot 2020-09-28 at 14 10 20" src="https://user-images.githubusercontent.com/28991/94430658-8dc1ad80-0194-11eb-8cc3-edb1587777c4.png">

**Comment by friedger** [comment]
I don't really see a value in self-certification on chain. You can better do that by putting a signed statement somewhere. It becomes more of a value if a person attests your self-certification. Then it becomes more of a valuable item. 

I don't want to see the stacks chain flooded with todo list item completed transactions. Ownership announcements seem more valuable to me.

![Screenshot from 2020-09-28 15-57-36](https://user-images.githubusercontent.com/1449049/94441716-5b6b7c80-01a3-11eb-8af0-0e633b0bba5f.png)

**Comment by markmhx** [comment]
Well, either way I think works for me. I don't think it's necessary to pick the right or perfect use case here from a UX perspective in any case. The exercise is mainly for learning how to develop with the relevant technologies, not figure out what kinds of apps or features to build.

Are you thinking that you'd list out all the registered todo lists in this extended todo app somehow? To provide a read view on that data as published on chain? That could complete the circle nicely.

**Comment by aulneau** [comment]
> From a UX perspective, I wonder if it'd be more meaningful to register the completion of specific todos on the blockchain instead of the todo lists themselves. This could manifest itself as an extended option of the current todos app, in that you can mark tasks as completed as normal / reversibly (in Gaia) or additionally mark them as completed permanently (on chain)

I think both are meaningful for different reasons. It sounds like this guide is more in line with starting to teach folks about how clarity can function as a decentralized aws lamda, rather than looking at it from the lens of what the consumer of the app can do. It also makes me think about ways in which functionality within radiks could be replicated/improved upon. This kind of tutorial really excites me because it starts on the path of showing how to incrementally move elements of your app to be more decentralized with clarity and the Stacks 2.0. @friedger would you say that is in line with what you were thinking?

**Comment by friedger** [comment]
> It sounds like this guide is more in line with starting to teach folks about how clarity can function as a decentralized aws lamda
@aulneau Yes, that sounds like what these kind of tutorials should achieve.

**Comment by friedger** [comment]
> Are you thinking that you'd list out all the registered todo lists in this extended todo app somehow? To provide a read view on that data as published on chain?

@markmhx There is already in the draft pull request the read view for the activity on the contract as well as more details about the last added todo list. A list of all registered lists is possible but with paging and filtering beyond this tutorial.

**Comment by friedger** [comment]
Here is a screenshot of the read-only view 
@markmhx Do you have suggestions for UI?

![Screenshot from 2020-09-29 22-21-09](https://user-images.githubusercontent.com/1449049/94611922-afa95600-02a2-11eb-869f-2a7903c641ee.png)

**Comment by markmhx** [comment]
I suggest putting that "read" information in the sharing component below the header and above the todos themselves, since that section has better context on "sharing" than the bottom of the screen.

I'd also suggest keeping the address out of the UI directly and linking instead to the Explorer.

@jasperjansz want to take a quick pass at updating the app's Figma designs to include the type of interaction and display that @friedger is shooting for here?

**Comment by agraebe** [comment]
> I'd also suggest keeping the address out of the UI directly and linking instead to the Explorer.

I agree with the notion that it might not be a good UX to show this. The address screen for the explorer is in the backlog, but as of today, one couldn't link to an address page on the explorer. @aulneau, anything to add?

**Comment by friedger** [comment]
The link goes to the to-do list, not the blockchain
