### ISSUE TITLE
Stacking contract reference

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#812]
The Stacking guide includes a [contract reference section](https://pr-805.docs.stacks.engineering/stacks-blockchain/stacking#stacking-contract). This section should be ...

- [x] Moved to the reference section in the docs
- [x] Auto-generated by upstream changes from `stacks-blockchain`

@lgalabru @kantai - do we need to create a new issue in the node project or is this good enough for you to prioritize this work?

cc @aulneau

**Comment by kantai** [comment]
This issue works for me. I have a working implementation of the docs generation, and will open a PR for it in the next day or so, and will update this issue when I do.

**Comment by kantai** [comment]
This PR adds generation of a JSON reference for boot contracts:

https://github.com/blockstack/stacks-blockchain/pull/1957

It also updates everyone's favorite PR robot so that it:

1. Formats the JSON using jq to make the PRs a little friendlier
2. Uses an e-mail address that should fix the issues with the CLA bot
3. Stores the new contracts reference JSON in the same directory as the Clarity reference.

**Comment by agraebe** [comment]
awesome! @aulneau what do we need to do to on the docs side?
