### ISSUE TITLE
Incorrect bitcoin ports in /start-mining 

### ISSUE THREAD

**Issue by radicleart** [blockstack/docs#961]
Instructions in https://docs.blockstack.org/start-mining on bitcoin testnet ports 

rpc_port = 18333
peer_port = 18332

These are actually reversed from the norm - bitcoin rpc port 18332 and peers bind on 18333 

See btc testnet wiki https://en.bitcoin.it/wiki/Testnet

**Comment by agraebe** [comment]
@CharlieC3 or @wileyj, you probably have more context. could you help?

**Comment by wileyj** [comment]
@radicleart is correct here, this came up in a chat a little while ago

**Comment by agraebe** [comment]
is this just a docs change or is there some container updates / devops work needed?

**Comment by wileyj** [comment]
Nothing on our end, no. This is a generic docs typo. 
I can address, but it'll take a little time before I can get to it. 

As @radicleart noted - the ports are confirmed to be reversed of what they should be:
They should be configured to use the default, since we rely on these ports using the default elsewhere (mining config):
```
rpc_port = 18332
peer_port = 18333
```

**Comment by agraebe** [comment]
I'll do it while I'm at it
