### ISSUE TITLE
Understand Stacks IA suggestion: Start with Accounts

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/docs#990]
Suggesting an order of: 
Overview
Testnet
Accounts
Transactions
Network
Proof of Transfer
Mining
Stacking
... 

PoX is and mining are hard to grok and unique to Stacks. Most integrators and builders don't need need to understand it to answer basic integration questions for their use case. And the accounts, transactions, and network guides probably answer 90% of what an integrator needs to answer. Curious if there is a counter argument.

**Comment by diwakergupta** [comment]
Yeah, "Understand Stacks" is getting unwieldy -- there's too many pages and agree a re-ordering might help. I'd even push testnet further down, it's not going be super relevant in a few weeks. How about:

* Overview (the goal of this page is a bit unclear to me. Has a bunch of overlaps with the technical specs too)
* Accounts
* Transactions
* Mining
* Stacking
* PoX
* Network
* Testnet
* ...

Thoughts @agraebe ?

**Comment by agraebe** [comment]
Yeah, the "Understand Stacks" chapter became a catch-all Stacks 2.0 area. This was OK while we created content to decrease the surface of fully undocumented parts of the platform. I agree that the next stage should be a more intuitive IA. As for the order, I don't think it matters _that_ much. I don't think folks will go top to bottom, page by page. It'd rather be based on keywords they think would cover stuff they're looking for. Orientation should be provided in the overview. 

Having said that, changing up the order with a more logical structure makes sense. Maybe it could simply be alphabetical to make scanning the list easier?

Otherwise, going with a step by step / top to bottom, order, I'd prefer:
- Overview (@diwakergupta this page can actually include the tech specs)
- Accounts
- Transactions
- Network (could include the testnet page)
- Mining
- Stacking
- PoX

Would also note that we currently have "blockchain/core" info (the IA covering the list above, tools guides (CLI, API, local dev), tutorials, and stacks 1.0 legacy info. We should remove the legacy info once it is irrelevant, that'll make the nav easier to scan. And maybe we should also create categories for "blockchain" and "tooling" pages?
