### ISSUE TITLE
IA suggestion: Accounts, Mining, Technical specs

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/docs#991]
See plenty of duplicative info there and not sure what the distinction is. Curious if we could combine into one 'Mining and Stacking' guide and then decompose the Technical spec page – most of that info can be merged with 'Mining and Stacking' and the rest can go to the respective guides for Accounts and Transactions.

**Comment by diwakergupta** [comment]
> See plenty of duplicative info there and not sure what the distinction is. Curious if we could combine into one 'Mining and Stacking' guide and then decompose the Technical spec page – most of that info can be merged with 'Mining and Stacking' and the rest can go to the respective guides for Accounts and Transactions.

The technical specs page was added for #780 and I do think it's nice to have a single-page that summarizes the key characteristics of various aspects of Stacks 2.0

Agree about the duplication, but not sure how effective a combined "mining and stacking" guide would be. We can imagine few different audiences here, with some, but not a lot of overlap:

- miners: want to mine STX. Probably care about things like binaries, deployment instructions, hardware requirements etc
- stackers: want to Stack their STX. Self-custody users will want an easy pointer to the wallet, others will probably look for delegation services
- integrators: the 3 tutorials for accounts, transactions and stacking probably address most of the needs in this bucket

**Comment by agraebe** [comment]
Agree that there's overlap because the content was created a bit in isolation initially. We should avoid duplicates. Some thoughts:
- I don't think though that stackers / end users are the audience for these pages, so would suggest we exclude them. They should be directed to the wallet page early on before they get to the docs.
- Mining and stacking were written for different audiences. I thought miners don't _need_ to know stacking details and stacking integrators wouldn't _need_ to understand mining details.
- We should probably make the "Start mining" page its own category. Everything related to mining fit into one page earlier, but now there are 3 pages. I'd suggest we move "Understand Stacks > Mining" to "Start mining > Overview".
- For the overlapping content in the tech specs, maybe we could keep it very concise and link out to further details. Just like @diwakergupta said, this page is basically a one-pager of Stacks 2.0 and it helps with orientation

**Comment by jeffdomke** [comment]
I just read through all of it and I'm reacting to the feeling that the technical specs guide has less technical detail than the Accounts, Transactions, and Network guides with the exception of PoX, Mining, and Stacking guides. Correspondingly those guides are light on detail and heavy on concept. My suggestion was one way to normalize across the guides: Keep all the technical detail in one structured set of areas and keep all the overview, index, and front matter in another area. 

Another approach would be to make the "Technical specs" page more of a technical jumpstart or TOC with quick headings and links out to details. I believe that is what Alex also just suggested.

**Comment by agraebe** [comment]
> Another approach would be to make the "Technical specs" page more of a technical jumpstart or TOC with quick headings and links out to details. I believe that is what Alex also just suggested.

+1 :)
